empresa = 'Digitron DGT'
nomes = ['Alex', 'Si']

print('title')
print(empresa.lower().title())
print('\n')
print('join')
print(', '.join(nomes))
print('\n')
print('split')
print(empresa.split(','))
print('\n')
print('capitalize')
print(empresa.lower().capitalize())
print('\n')
print('repleace')
print(empresa.replace('DGT', 'Amazonia'))
print('\n')
print('upper')
print(empresa.upper())
print('\n')
print('lower')
print(empresa.lower())
print('\n')
print('find')
print(empresa.find('d'))
print('\n')
print('count')
print(empresa.lower().count('d'))
